# Generated by Django 4.0 on 2021-12-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_client_order_stock_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
