# Generated by Django 4.0 on 2022-01-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_order_time_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Sell Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(),
        ),
    ]
