# Generated by Django 4.0 on 2022-01-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_order_date_alter_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='volume',
            new_name='market_cap',
        ),
        migrations.AddField(
            model_name='stock',
            name='qty',
            field=models.IntegerField(default=100),
        ),
    ]
