# Generated by Django 4.0 on 2022-01-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_client_name_client_worth_order_date_order_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(verbose_name='Sell Date/Time'),
        ),
    ]
